export const ANIMAL_MODEL = 'ANIMAL_MODEL';
export const FEED_MODEL = 'FEED_MODEL';
export const BREEDING_MODEL = 'BREEDING_MODEL';
export const VACCINATION_MODEL = 'VACCINATION_MODEL';
export const ANIMAL_PRODUCTION_MODEL = 'ANIMAL_PRODUCTION_MODEL';


