export const CONTACT_MODEL = "CONTACT_MODEL";
export const CONTACT_FINANCES_MODEL = "CONTACT_FINANCES_MODEL";
export const CONTACT_ACTIVITY = "CONTACT_ACTIVITY";
export const CONTACT_DOCUMENT_MODEL = "CONTACT_DOCUMENT_MODEL";