export const ASSET_MANAGEMENT_MODEL = "ASSET_MANAGEMENT_MODEL";
export const ASSET_INSPECTION_MODEL = "ASSET_INSPECTION_MODEL";
export const ASSET_FINANCIAL_MODEL = "ASSET_FINANCIAL_MODEL";
export const ASSET_LOCATION_MODEL = "ASSET_LOCATION_MODEL";