export const CROP_MODEL = 'CROP_MODEL';
export const IRRIGATION_MODEL = 'IRRIGATION_MODEL';
export const FERTILIZER_PESTICIDE_MODEL = 'FERTILIZER_PESTICIDE_MODEL';
export const FINANCIAL_MODE = 'FINANCIAL_MODE';